version: '2'
services:
  consul:
    image: appcelerator/consul:latest-server
    hostname: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command:
      [ "docker-entrypoint.sh elasticsearch -bootstrap"]

  pilot:
    image: appcelerator/amp-pilot:latest
    volumes:
      - /bin/amppilot:/bin/amppilot
    environment:
      CONSUL: consul:8500
    labels:
      - "io.appcelerator.amp.build.mounts=/bin/amppilot"
    depends_on:
      - consul

  elasticsearch-amp:
    build: .
    image: appcelerator/elasticsearch-amp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /bin/amppilot:/bin/amppilot:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      DEPENDENCIES: ""
      CONSUL: consul:8500
      SERVICE_NAME: elasticsearch-amp
      AMPPILOT_LAUNCH_CMD: elasticsearch
    command: /bin/amppilot/pilotLoader
    labels:
      - "io.appcelerator.amp.build.mounts=/var/run/docker.sock,/bin/amppilot"
    depends_on:
      - consul
      - pilot

  sut:
    image: appcelerator/sut
    build:
      context: ./sut
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch-amp
